const DT = 0.02; 
        const INITIAL_PARAMS = { m: 2.0, k: 1.0, c: 0.5, target: 5.0 };

        // ==========================================
        // 核心控制器配置字典 (修正与重构版)
        // ==========================================
        const CONTROLLER_CONFIGS = {
            // === 【1. 经典线性体系】 ===
            'OpenLoop': { category: '01. 经典线性体系', name: '开环前馈 (Open Loop)', desc: '无反馈，遇干扰即失效。', eq: 'u = k · r', tuning: '完全依赖对环境弹簧系数(K)的预判，一旦参数摄动或有扰动，必然产生静差。', params: { u_static: [5.0, 0, 50, 0.1] } },
            'P': { category: '01. 经典线性体系', name: 'P控制 (比例)', desc: '输出与误差成正比，存在稳态误差。', eq: 'u = K_p · e', tuning: 'Kp调大能加快收敛，但由于系统缺乏阻尼会造成严重超调，永远无法彻底消除弹簧拉力带来的静差。', params: { kp: [40, 0, 100, 1] } },
            'PI': { category: '01. 经典线性体系', name: 'PI控制 (比例-积分)', desc: '消除稳态误差，但增加超调。', eq: 'u = K_p · e + K_i ∫e dt', tuning: 'Ki从极小值开始加。Ki过大将导致系统积累过多能量，引起长时间的低频震荡（积分饱和）。', params: { kp: [30, 0, 100, 1], ki: [5, 0, 50, 0.1] } },
            'PD': { category: '01. 经典线性体系', name: 'PD控制 (比例-微分)', desc: '微分相当于电子阻尼，减少超调。', eq: 'u = K_p · e - K_d · v', tuning: '大幅增加Kd能提供强大的“电子阻尼”有效抑制超调。缺点是现实中会放大高频噪声。', params: { kp: [40, 0, 100, 1], kd: [10, 0, 50, 0.1] } },
            'PID': { category: '01. 经典线性体系', name: 'PID控制 (比例-积分-微分)', desc: '工业万金油，综合快、准、稳。', eq: 'u = K_p · e + K_i ∫e dt - K_d · v', tuning: '先提Kp让系统动起来，再加Kd把震荡压平，最后补微小Ki消除贴不到目标的稳态静差。', params: { kp: [40, 0, 100, 1], ki: [10, 0, 50, 0.1], kd: [20, 0, 50, 0.1] } },
            'IPD': { category: '01. 经典线性体系', name: 'I-PD (微分先行PID)', desc: 'P和D仅作用于状态，避免指令突变冲击。', eq: 'u = K_i ∫e dt - K_p · x - K_d · v', tuning: 'Kp不作用于目标偏差，系统对目标阶跃的初始响应会变平缓，适合限制加速度的机械结构。', params: { kp: [40, 0, 100, 1], ki: [10, 0, 50, 0.1], kd: [20, 0, 50, 0.1] } },
            '2DOF-PID': { category: '01. 经典线性体系', name: '二自由度 PID', desc: '前馈系数独立优化跟踪能力，削弱超调。', eq: 'u = K_p(b·r - x) + K_i ∫e dt - K_d · v', tuning: '微调前置权重b(0.3~0.8)。调小b能在不影响抗干扰能力的前提下，大幅削弱阶跃指令超调。', params: { kp: [40, 0, 100, 1], ki: [10, 0, 50, 0.1], kd: [20, 0, 50, 0.1], b: [0.5, 0, 1, 0.05] } },
            'IncPID': { category: '01. 经典线性体系', name: '增量式 PID', desc: '自带抗积分饱和特性。', eq: 'Δu = K_p Δe + K_i e + K_d Δ²e', tuning: '注意！增量式PID的参数量级通常远小于位置式。Ki主导稳态速度，Kp负责抗瞬态扰动。适合高频定周期采样环境。', params: { kp: [10, 0, 100, 1], ki: [0.5, 0, 10, 0.01], kd: [5, 0, 50, 0.1] } },
            'PI-D': { category: '01. 经典线性体系', name: 'PI-D 控制', desc: 'D仅作用于反馈测量避免突变，P和I作用于误差。', eq: 'u = K_p e + K_i ∫e - K_d v', tuning: '比标准 PID 更柔和的指令跟踪。适合防止启动时 D 项对指令跳变产生的求导尖峰刺透执行器。', params: { kp: [40, 0, 100, 1], ki: [10, 0, 50, 0.1], kd: [20, 0, 50, 0.1] } },
            'Nested-PID': { category: '01. 经典线性体系', name: '串级 PID (Nested PID)', desc: '外环控位置算基准速度，内环控速度算最终推力。', eq: 'v_d = P(r-x); u = P(v_d-v) + I∫', tuning: '无人机/机械臂必用。内环 Kp_in 必须调得极其刚猛以压制速度，外环 Kp_out 只需温柔给令。', params: { kp_out: [5, 0.1, 20, 0.1], kp_in: [30, 1, 100, 1], ki_in: [10, 0, 50, 0.1] } },

            // === 【2. 频域与最优理论】 ===
            'PolePlacement': { category: '02. 频域与最优理论', name: '极点配置 (状态反馈)', desc: '将闭环极点配置到期望位置。', eq: 'u = -K₁ x - K₂ v + (K₁+k) r', tuning: '极点 p1, p2 设为正数。值越大闭环极点越深埋左半平面，收敛极快但极易导致执行器饱和。', params: { p1: [2, 0.1, 10, 0.1], p2: [3, 0.1, 10, 0.1] } },
            'LQR': { category: '02. 频域与最优理论', name: 'LQR (线性二次型最优)', desc: '最小化状态偏差和能量消耗代价函数。', eq: 'u = -K_{lqr} [x-r, v]^T', tuning: 'Q_x惩罚位置误差，R_weight惩罚能量消耗。因缺乏积分项，在带弹簧系统中必然存在静差。', params: { q_x: [100, 1, 500, 1], q_v: [10, 0.1, 50, 0.1], r_weight: [1, 0.1, 20, 0.1] } },
            'LQG': { category: '02. 频域与最优理论', name: 'LQG (包含卡尔曼滤波)', desc: '在测量噪声中利用卡尔曼滤波器提取最佳状态反馈。', eq: 'u = -K_{lqr} [x̂-r, v̂]^T \\ (x̂ 由卡尔曼估计)', tuning: '通过拉高 Q_x/R_w 提高跟踪精度，代价是会让执行器更敏感地响应滤波残留带来的高频颤振。', params: { q_x: [100, 1, 500, 1], q_v: [10, 0.1, 50, 0.1], r_w: [1, 0.1, 20, 0.1] } },
            'LQR-I': { category: '02. 频域与最优理论', name: '带积分 LQR (LQI)', desc: '最正宗的无静差状态反馈，将状态扩维加入积分误差向量。', eq: 'u = -K [x, v, ∫e]^T', tuning: 'Q_i 就是对稳态不完美度的惩罚！只要你不瞎调，它就是完美抗衡一切常量扰动和偏置的最优解法。', params: { q_x: [100, 1, 500, 1], q_v: [10, 0.1, 50, 0.1], q_i: [500, 10, 2000, 10] } },
            'MPC': { category: '02. 频域与最优理论', name: 'MPC (模型预测控制)', desc: '预测未来系统轨迹并在线优化求解。', eq: 'u = argmin_{u} [ (x_{pred}-r)^2 + λu^2 ]', tuning: 't_pred为预测视野，较短系统偏激进；Lambda为控制成本惩罚，调大会让控制力更加丝滑。', params: { t_pred: [0.5, 0.05, 2.0, 0.05], lambda: [0.01, 0.001, 1, 0.001] } },
            'Deadbeat': { category: '02. 频域与最优理论', name: '无差拍控制 (Deadbeat)', desc: '极点配置在Z域原点，试图最少步数内消除误差。', eq: 'u = (m/T²)K·e - (m/T+c)K·v + k·x', tuning: '理论可在2拍内归零。离散化中kp_scale过高极易因为步长当场发散爆炸，建议维持 0.5。', params: { kp_scale: [0.5, 0.1, 2.0, 0.1] } },
            'H-Infinity': { category: '02. 频域与最优理论', name: 'H-∞ 鲁棒状态反馈', desc: '基于黎卡提方程设计，最小化无穷范数抑制干扰。', eq: 'u = P_{22} e - P_{12} v \\ (P 由 H_∞解出)', tuning: 'Gamma是干扰抑制上界。逼近临界值能获得地狱级鲁棒性，通过Q_x加强性能。', params: { gamma: [2.0, 1.1, 10, 0.1], q_x: [100, 10, 500, 10] } },
            'QFT-LeadLag': { category: '02. 频域与最优理论', name: 'QFT / 超前-滞后补偿', desc: '定量反馈设计，提升系统频域相位裕度。', eq: 'C(s) = K_{gain} (s+z) / (s+p)', tuning: '配置 Zero < Pole 以实现超前补偿(相当于频域D项)，Gain控制总带宽。频域教徒的最爱。', params: { gain: [50, 1, 100, 1], zero: [2.0, 0.1, 10, 0.1], pole: [20, 1, 50, 1] } },
            'IMP-Servo': { category: '02. 频域与最优理论', name: '内模原理伺服控制 (IMP)', desc: '增广方程引入指令积分，保证绝对无静差跟踪。', eq: 'u = -K_x x - K_v v + K_i ∫e dt + k·r', tuning: '弥补了LQR无法消除静差的遗憾。拉高 Q_e 像利剑一样劈开静差，但易引起初始大幅超调。', params: { q_e: [1000, 10, 2000, 10], q_x: [50, 1, 100, 1], r_u: [1, 0.1, 20, 0.1] } },
            'Preview': { category: '02. 频域与最优理论', name: '预见控制 (Preview Control)', desc: '利用未来已知目标，提前动作。', eq: 'u = K_p e - K_d v + K_{prev} ∑ γ^i r(t+i)', tuning: '当目标点是定值时效果类似增强前馈。K_prev越大，系统在到达目标前就越会“提前蓄力”。', params: { kp: [40, 1, 100, 1], kd: [20, 0.1, 50, 0.1], k_prev: [0.3, 0.01, 2.0, 0.01] } },

            // === 【3. 非线性结构控制】 ===
            'BangBang': { category: '03. 非线性结构控制', name: 'Bang-Bang 控制', desc: '极粗暴双位控制，产生极限环震荡。', eq: 'u = F_{max} · sgn(e)', tuning: 'Force必须远大于稳态拉力。必然产生极限环震荡，调大force只会让它震得更猛烈。', params: { force: [20, 0, 200, 1] } },
            'BangBang-Zone': { category: '03. 非线性结构控制', name: '死区比例 BangBang', desc: '远端全开，进入设定区域后平滑切换为比例控制防震。', eq: 'u = F_{max} (|e|>Z) | K_p e (|e|<Z)', tuning: 'Zone 必须包住 P控制 能吃住的最大超调。完美衔接了非线性的快与线性的稳。', params: { force: [50, 10, 200, 1], zone: [0.5, 0.1, 2.0, 0.1], kp: [40, 1, 100, 1] } },
            'Relay': { category: '03. 非线性结构控制', name: '滞回继电控制 (Relay)', desc: '引入死区滞回区间，消除高频抖振。', eq: 'u = F_{max} (|e| > d) 带滞回', tuning: 'Deadzone（死区）设定了你能容忍的稳态静差。进了这个区间控制就“躺平”，消除了颤振。', params: { force: [20, 10, 200, 1], deadzone: [0.1, 0.01, 1, 0.01] } },
            'TimeOptimal': { category: '03. 非线性结构控制', name: '时间最优相平面法', desc: '利用相平面切换曲线。', eq: 'u = F_{max} · sgn(e - v|v|/(2a_{max}))', tuning: '算法依据物理方程在“全速推进”和“全速刹车”间寻找唯一的完美切换点，原点处引入线性过渡防溢出。', params: { force: [20, 10, 200, 1] } },
            'FeedbackLin': { category: '03. 非线性结构控制', name: '反馈线性化 (计算力矩)', desc: '抵消不利动态，嵌入期望阻尼响应。', eq: 'u = m(K_p e - K_d v) + cv + kx', tuning: 'Kp决定目标追击烈度。为了保证绝不超调的临界阻尼特性，Kd 必须设定为 2 * sqrt(Kp)。', params: { kp: [25, 1, 100, 1], kd: [10, 0.1, 50, 0.1] } },
            'Backstepping': { category: '03. 非线性结构控制', name: '反步法 (Backstepping)', desc: '构造李雅普诺夫虚拟控制律，全局稳定。', eq: 'u = m(-z_1 - c_2 z_2 + c_1 v) + kx + cv', tuning: 'c1决定子系统收敛速度，c2决定实际控制侧响应。两者最好协同放大，若差距过大易造成脱节。', params: { c1: [5, 0.1, 20, 0.1], c2: [5, 0.1, 20, 0.1] } },
            'DSC': { category: '03. 非线性结构控制', name: '动态面控制 (DSC)', desc: '一阶低通虚拟面滤波器解决“微分爆炸”。', eq: 'τ ż + z = α₁ ;  u = m(ż - c_2 s_2 - s_1) + kx + cv', tuning: 'Tau为虚拟面滤波时间常数，取极小(0.01~0.05)。过大会导致滤波面严重滞后引发跟踪超调。', params: { c1: [5, 0.1, 20, 0.1], c2: [5, 0.1, 20, 0.1], tau: [0.05, 0.01, 0.5, 0.01] } },
            'TDC': { category: '03. 非线性结构控制', name: '时间延迟控制 (TDC)', desc: '利用极小时间延迟数据抵消未知动态。', eq: 'u(t) = u(t-dt) + m(a_{des} - a(t-dt))', tuning: '暴力而有效。M_nom 最好保持在真实值的 0.5倍~2倍 之间，否则前馈抵消彻底失效引发崩溃。', params: { m_nom: [2.0, 0.5, 10, 0.1], kp: [25, 1, 100, 1], kd: [10, 0.1, 50, 0.1] } },
            'NDC': { category: '03. 非线性结构控制', name: '非线性阻尼控制 (NDC)', desc: '注入非线性阻尼项 e²v，大误差大阻尼。', eq: 'u = K_p e - K_d v - K_{nd} e^2 v', tuning: 'K_nd 控制非线性阻尼。大位移时阻尼狂飙按住超调，逼近目标阻尼归零保障高敏捷。极其实用。', params: { kp: [40, 1, 100, 1], kd: [10, 0, 50, 0.1], k_nd: [5, 0, 50, 0.1] } },
            'CFTC': { category: '03. 非线性结构控制', name: '连续有限时间控制 (CFTC)', desc: '连续分数次幂反馈，严格有限时间内到达0。', eq: 'u = K_p |e|^α sgn(e) - K_d |v|^β sgn(v) + kr', tuning: 'Alpha越小收敛越绝对，但过小(如<0.5)在离散机系上原点极易产生无穷大导数从而震荡或崩溃。', params: { kp: [30, 1, 100, 1], kd: [15, 1, 50, 1], alpha: [0.8, 0.1, 0.99, 0.01] } },

            // === 【4. 滑模变结构家族】 ===
            'SMC': { category: '04. 滑模变结构家族', name: '传统滑模控制 (SMC)', desc: '严格等效控制结合切换项。绝对鲁棒，但有高频抖振。', eq: 'u = u_{eq} + K_{gain} sat(s/ε)', tuning: 'K_gain只需稍大于未知扰动。Epsilon边界层放宽能抹平控制力的高频抖振，但会带来微小静差。', params: { c_surface: [5, 0.1, 20, 0.1], k_gain: [10, 1, 100, 1], eps: [0.1, 0.01, 2, 0.01] } },
            'VSC-RL': { category: '04. 滑模变结构家族', name: '指数趋近律滑模', desc: '配置滑动面指数导数，平滑到达相。', eq: 'u = u_{eq} + m(ε sgn(s) + K_{rl} s)', tuning: 'K_rl 主导远端指数逼近速度，Eps 主导近端匀速穿刺滑模面。巧妙组合两者能让到达轨迹极速且平滑。', params: { c_surface: [5, 0.1, 20, 0.1], eps: [5, 0.1, 50, 0.1], k_rl: [10, 0.1, 50, 0.1] } },
            'ISMC': { category: '04. 滑模变结构家族', name: '积分滑模控制 (ISMC)', desc: '引入积分项消除到达相，全程鲁棒。', eq: 'u = kx + cv + K_{gain} sat(s/ε) \\ (s含积分)', tuning: '自带积分项，无论初始多偏系统都在滑动面上，全程免疫匹配扰动。C1/C2决定收敛特质。', params: { c1: [5, 0.1, 20, 0.1], c2: [5, 0.1, 20, 0.1], k_gain: [20, 1, 100, 1] } },
            'TSMC': { category: '04. 滑模变结构家族', name: '终端滑模控制 (TSMC)', desc: '引入分式次幂滑动面，有限时间内绝对收敛至零。', eq: 'u = u_{eq} + K_{gain} sgn(-v + β e^α)', tuning: 'Alpha必属于(0,1)。非线性吸引子使近端收敛极快，但原点存在不可消除的奇异抖振问题。', params: { beta: [5, 0.1, 20, 0.1], alpha: [0.8, 0.1, 0.99, 0.01], k_gain: [15, 1, 100, 1] } },
            'FTSMC': { category: '04. 滑模变结构家族', name: '快速终端滑模 (FTSMC)', desc: '结合线性与非线性终端滑模，远端快速近端有限。', eq: 'u = u_{eq} + K_{gain} sgn(-v + c_1 e + c_2 e^q)', tuning: '最极客的滑模。远端靠 C1(线性) 狂飙，近端靠 C2和Q(次幂) 收尾。参数微调较难。', params: { c1: [4, 0.1, 20, 0.1], c2: [2, 0.1, 10, 0.1], q: [0.8, 0.1, 0.99, 0.01], k_gain: [15, 1, 100, 1] } },
            'ASMC': { category: '04. 滑模变结构家族', name: '自适应滑模控制', desc: '根据滑动面动态自适应调节切换增益。', eq: 'u = u_{eq} + K̂ sgn(s) \\ ( dK̂/dt = γ|s| )', tuning: 'Gamma主导切换增益K_hat的学习速度。无需预知干扰强度，在线把自己武装到恰好镇压干扰的力度。', params: { c_surface: [5, 0.1, 20, 0.1], gamma: [50, 1, 200, 1] } },
            'SuperTwisting': { category: '04. 滑模变结构家族', name: '超螺旋滑模 (2阶SMC)', desc: '将高频切换隐藏在积分项内部，极大削弱抖振。', eq: 'u = u_{eq} + m(λ√|s|sgn(s) + W∫sgn(s) dt)', tuning: '解决抖振的终极方案！Lambda和W黄金配比通常为 Lambda=1.5*sqrt(W)。观察红线，几乎完美平滑！', params: { c: [5, 0.1, 20, 0.1], lambda: [10, 1, 50, 1], W: [20, 1, 100, 1] } },
            'LevantHOSM': { category: '04. 滑模变结构家族', name: 'Levant 鲁棒精确微分滑模', desc: '通过高阶滑模精确微分器无延迟滤除噪声提取理想导数。', eq: 'u = K_{gain} sat(s_{Levant}/ε) + k·r', tuning: '无惧传感器噪声。L1/L2是观测器增益，L1过小导致误差放大，调控二者可在抗噪与跟随间折中。', params: { l1: [10, 1, 50, 1], l2: [20, 1, 100, 1], c_surf: [5, 0.1, 20, 0.1], k_gain: [20, 1, 100, 1] } },
            'VariableG-SMC': { category: '04. 滑模变结构家族', name: '变增益滑模 (Variable-Gain SMC)', desc: '切换增益非恒定，基于状态范数动态扩张。', eq: 'u = u_{eq} + (k_0 + k_1|x|) sgn(s)', tuning: 'K_1|x| 在远端获得极高增益狂暴回扯，近端仅留 K_0 温柔保底。化解了恒定高增益的机械损伤。', params: { c_surf: [5, 0.1, 20, 0.1], k0: [5, 0.1, 20, 0.1], k1: [10, 0.1, 50, 0.1] } },
            'AW-PI': { category: '04. 滑模变结构家族', name: '抗饱和 PI (Anti-Windup PI)', desc: '遇限幅时切断积分通道，经典钳位反算算法。', eq: 'I_{dot} = e - K_a (u - sat(u))', tuning: '由于它处理强约束限幅极其鲁棒，暂放此类。K_a 为反算系数，优雅钳位，解限后瞬间恢复战力。', params: { kp: [30, 0, 100, 1], ki: [20, 0, 100, 0.1], k_aw: [5, 0.1, 20, 0.1] } }, 

            // === 【5. 数据驱动与智能】 ===
            'NPID': { category: '05. 数据驱动与智能', name: '韩氏非线性 PID', desc: '利用 fal 函数实现“小误差大增益，大误差小增益”。', eq: 'u = K_p fal(e) + K_i ∫fal(e) + K_d fal(-v)', tuning: 'Alpha调低(<0.7)能极大放大微小静差的权重实现高敏捷；Delta防止原点导数无穷大，必设极小值(0.1)。', params: { kp: [40, 1, 100, 1], ki: [10, 0, 50, 0.1], kd: [20, 1, 50, 0.1], alpha: [0.75, 0.1, 0.9, 0.05], delta: [0.1, 0.01, 1, 0.01] } },
            'MRAC': { category: '05. 数据驱动与智能', name: 'MRAC (模型参考自适应)', desc: '在线自适应调整参数，追踪预设理想模型。', eq: 'u = θ_r r + θ_x x + θ_v v \\ (dθ/dt ∝ e_m)', tuning: 'Gamma学习率决定追踪紫色参考线的积极性。过大会引发参数震荡。Wn/Zeta决定理想模型动态特质。', params: { gamma: [10, 0.1, 50, 0.1], wn: [2, 0.5, 10, 0.1], zeta: [1, 0.1, 2, 0.1] } },
            'STR': { category: '05. 数据驱动与智能', name: '自校正调节器 (STR)', desc: '在线辨识系统环境参数，实时求解极点配置。', eq: 'u = mω² r - (mω² - k̂)x - (2mζω - ĉ)v', tuning: '底层偷偷计算估测弹簧系数(K)和阻尼(C)，摸清底细后瞬间施展极点配置实现完美控制。', params: { gamma: [5, 0.1, 50, 0.1], wn: [2, 1, 10, 0.1], zeta: [1, 0.1, 2, 0.1] } },
            'MFAC': { category: '05. 数据驱动与智能', name: '无模型自适应 (MFAC)', desc: '引入广义误差面解决二阶物理系统纯积分导致的发散问题。', eq: 'u(k)=u(k-1)+[ρ φ/(λ+φ²)]e^* \\ φ(k)=φ(k-1)+[ηΔu/(μ+Δu²)](Δy-φΔu)', tuning: '基础MFAC等效纯积分，必须用 Kd 引入电子阻尼(广义误差面)。Rho 控制步长，Eta 决定 φ 学习率，Lambda 防除零发散。', params: { rho: [0.5, 0.01, 2, 0.01], kd: [15.0, 0, 50, 0.1], lambda: [1.0, 0.1, 10, 0.1], eta: [1.0, 0.1, 5, 0.1], mu: [1.0, 0.1, 5, 0.1] } },
            'iPID': { category: '05. 数据驱动与智能', name: '超局部智能 PID (iPID)', desc: '在线估计极复杂动态项并直接代数对消。', eq: 'u = (-F̂ + K_p e - K_d v) / α', tuning: 'Alpha必须恰当缩放；Tau滤波器时间常数越小则F估计越灵敏，但噪声放大风险剧增。未知干扰杀手。', params: { alpha: [1.0, 0.01, 5, 0.01], kp: [40, 1, 100, 1], kd: [20, 0.1, 50, 0.1], tau: [0.05, 0.01, 0.5, 0.01] } },
            'U-Model': { category: '05. 数据驱动与智能', name: 'U-Model 动力学求根', desc: 'Newton-Raphson 迭代法在线实时求解控制多项式的根。', eq: 'u(k) = u(k-1) + μ(r - ŷ) / (∂y/∂u) + PD', tuning: '牛顿迭代步长 Step_nr 非常敏感，过大必炸。将复杂的非线性寻根问题通过局部线性化映射，对时变系统有效。', params: { kp: [20, 1, 50, 1], kd: [10, 0.1, 20, 0.1], step_nr: [0.5, 0.01, 1, 0.01] } },
            'ESC': { category: '05. 数据驱动与智能', name: '极值寻优控制 (ESC)', desc: '注入探测正弦波实时计算成本梯度寻优。', eq: 'u = u_{pd} + u_{bias} + a·sin(ωt)', tuning: '控制线的极高频振动是它的“寻优触角”。通过评估扰动代价反向调整偏置(Bias)，极度魔幻。', params: { k_esc: [50, 1, 100, 1], omega: [15, 1, 50, 1], amp: [1.0, 0.1, 10, 0.1] } },
            'BELBIC': { category: '05. 数据驱动与智能', name: '大脑情感仿生控制 (BELBIC)', desc: '哺乳动物边缘系统神经模型，纯正仿生学。', eq: 'u = A - O + k·r \\ (A:杏仁核, O:眶额皮层)', tuning: '杏仁核主攻快速惩罚性学习，眶额皮层负责遗忘平抑过冲。调节感觉权重(We/Wv)模拟情绪对行动影响。', params: { a_A: [10, 0.1, 20, 0.1], a_O: [5, 0.1, 20, 0.1], w_e: [2, 0.1, 5, 0.1], w_v: [1, 0.1, 5, 0.1] } },
            'Linear-Actor-Critic': { category: '05. 数据驱动与智能', name: '线性 Actor-Critic (RL)', desc: '在线自适应评价与动作策略更新。修正版 DDPG 概念。', eq: 'V = θ_c^T φ(x), u = θ_a^T φ(x) + r \\ (TD_err更新)', tuning: 'Alpha_a (演员学习率)直接决定动作调整速度。基于 TD 误差(时间差分)动态进化网络权重。', params: { alpha_c: [2.0, 0.1, 10, 0.1], alpha_a: [5.0, 0.1, 20, 0.1], gamma_rl: [0.95, 0.8, 0.99, 0.01] } },
            'Gradient-PID': { category: '05. 数据驱动与智能', name: '基于梯度在线 PID (代IFT)', desc: '利用在线计算的误差敏感度(梯度)动态调整 PID 参数。', eq: 'K_p = K_p - γ_p e (∂e/∂K_p)', tuning: '无需离线实验。只要误差存在，系统就能根据敏捷梯度(Gamma_p/d)自动扭转 PID 使其最优。', params: { gamma_p: [0.5, 0.01, 2.0, 0.01], gamma_d: [0.1, 0.01, 1.0, 0.01], kp0: [10, 1, 50, 1] } },

            // === 【6. 融合与复合架构】 ===
            'DOB': { category: '06. 融合与复合架构', name: 'DOB (扰动观测器框架)', desc: '【逆模型 + PD】估算外部总扰动直接补偿。', eq: 'u = K_p e - K_d v - d̂ \\ (d̂=LPF(u-u_{nom}))', tuning: '调高W_c可光速识别扰动对冲，但在真实带噪声系统中会让你付出全系高频抖动的惨痛代价。', params: { w_c: [50, 1, 100, 1], kp: [40, 1, 100, 1], kd: [20, 0.1, 50, 0.1] } },
            'IMC': { category: '06. 融合与复合架构', name: '内模控制 (IMC)', desc: '【内部模型 + PID】引入过程模型逆修正扰动。', eq: 'u = K_p(r\' - x) + K_i ∫(r\' - x) - K_d v', tuning: '后台跑名义模型，一旦现实跑偏，把偏差送给PI狂补。稳健性取决于已知模型底子有多准。', params: { kp: [40, 1, 100, 1], ki: [10, 0.1, 50, 0.1], kd: [20, 0.1, 50, 0.1] } },
            'ADRC': { category: '06. 融合与复合架构', name: 'LADRC (线性自抗扰)', desc: '【LESO + LSEF】视未知为总扰动进行观测对消。', eq: 'u = (w_c²(r - z₁) - 2w_c z₂ - z₃) / b₀', tuning: 'W_o(观测器带宽)推荐设为 W_c(控制反馈带宽) 的3-5倍。B0只要数量级不出错，剩下全靠观测器逆天强补。', params: { w_o: [30, 5, 100, 1], w_c: [10, 1, 50, 1], b0: [0.5, 0.01, 5, 0.01] } },
            'NL-ADRC': { category: '06. 融合与复合架构', name: 'NL-ADRC (非线性自抗扰)', desc: '【NLESO+NLSEF】全盘非线性fal函数榨取抗扰极限。', eq: 'u = (w_c² fal(r-z₁) - 2w_c z₂ - z₃) / b₀', tuning: '韩京清教授原版。非线性扩张在极小偏差下有非凡感知力。Delta值越小非线性切换越猛。', params: { w_o: [30, 5, 100, 1], w_c: [10, 1, 50, 1], b0: [0.5, 0.01, 5, 0.01], delta: [0.1, 0.01, 0.5, 0.01] } },
            'ARC': { category: '06. 融合与复合架构', name: '自适应鲁棒控制 (ARC)', desc: '【自适应 + 滑模】参数在线学习，高频干扰滑模镇定。', eq: 'u = m̂(-cv) + kx + cv + K_s s + K_n sgn(s)', tuning: '双剑合璧。Gamma严格跟随观测信息学习系统的质量漂移，瞬发打击则交由K_s/K_n滑模强行镇压。', params: { gamma: [5, 0.1, 20, 0.1], c: [5, 0.1, 20, 0.1], k_s: [15, 0, 50, 1], k_n: [5, 0, 20, 0.5] } },
            'ESO-SMC': { category: '06. 融合与复合架构', name: '扩张观测器+滑模 (ESO-SMC)', desc: '【LESO + SMC】观测器补偿90%扰动，滑模镇定残差。', eq: 'u = (-c·z₂ - z₃ + K·sat(s)) / b₀', tuning: '由于前置ESO已经挖走了几乎所有的可观测干扰，滑模的K_gain只需设个极小的数值保底，从而实现无抖振极致平滑。', params: { w_o: [30, 5, 100, 1], c_surface: [5, 0.1, 20, 0.1], k_gain: [10, 1, 50, 1], b0: [0.5, 0.01, 5, 0.01] } },
            'L1': { category: '06. 融合与复合架构', name: 'L1 自适应控制', desc: '【极高增益自适应 + LPF】完美解耦自适应速度与鲁棒性。', eq: 'u = LPF(u_{pd} - m·θ̂_x) \\ dθ̂_x/dt = -γ(v̂ - v)', tuning: 'Gamma可以丧心病狂地拉到1000。由于使用了真实预测状态v̂，T_lpf死死兜底隔离高频发散，绝对稳。', params: { gamma: [1000, 100, 2000, 100], t_lpf: [0.05, 0.01, 0.5, 0.01], wn: [2, 0.5, 10, 0.1], zeta: [1, 0.1, 2, 0.1] } },
            'I-and-I': { category: '06. 融合与复合架构', name: 'I&I 浸入与不变自适应', desc: '不要求参数收敛，仅要求目标流形收敛，瞬间跟踪极佳。', eq: 'u = K_p e - K_d v + d̂ \\ d̂ = z - λmv \\ dz/dt = λu - λd̂', tuning: '不再纠结参数准确性。适当拔高 Lambda，系统将在极短的时间内强迫轨迹进入安全流形空间，超调控制完爆经典MRAC。', params: { gamma: [10, 0.1, 50, 0.1], lambda: [5, 1, 50, 1], kp: [30, 1, 100, 1], kd: [15, 0.1, 50, 0.1] } },
            'AdaptBackstepping': { category: '06. 融合与复合架构', name: '自适应反步法', desc: '【反步+辨识】虚拟控制律严格基于Lyapunov推导参数自适应律。', eq: 'u = -z₁ - c₂z₂ - m̂ c₁ v + kx + cv \\ d(m̂)/dt = γ z₂ c₁ v', tuning: '极其优雅的数学推导连携反应。即使遇到质量骤变也能在几秒内将其收敛抵消稳住局面。', params: { c1: [5, 0.1, 20, 0.1], c2: [5, 0.1, 20, 0.1], gamma_m: [2, 0.1, 20, 0.1] } },
            'T-DOB': { category: '06. 融合与复合架构', name: '时延估测观测器 (T-DOB)', desc: '直接利用上一时刻的推力和时延微积分估测扰动。', eq: 'd̂ = u(t-d) - M a(t-d)', tuning: '这是 DOB 家族最务实的一派。只要 D_delay 足够小，它连非最小相位系统都能给你硬掰回正轨。', params: { m_nom: [2.0, 0.5, 10, 0.1], delay_d: [3, 1, 10, 1], kp: [40, 1, 100, 1], kd: [20, 0.1, 50, 0.1] } },

            // === 【7. 前沿与新型约束】 ===
            'PPC': { category: '07. 前沿与新型约束', name: '规定性能控制 (PPC)', desc: '非线性映射保证瞬态误差绝对锁死在指数衰减漏斗内。', eq: 'u = K_p z_{ppc} - K_d v + kr \\ (z=\\frac{1}{2}\\ln\\frac{1+e/ρ}{1-e/ρ})', tuning: '硬性要求：Rho_0(漏斗初高)必须严格大于指令初差！L是漏斗闭合速度，调高可强制光速落位。', params: { kp: [30, 1, 50, 1], kd: [10, 0, 20, 0.1], rho_0: [6.0, 1, 10, 0.1], rho_inf: [0.1, 0.01, 1, 0.01], l: [1.0, 0.1, 5, 0.1] } },
            'BLF': { category: '07. 前沿与新型约束', name: '障碍李雅普诺夫 (BLF)', desc: '状态逼近安全边界 $k_b$ 时，控制力趋于无穷。', eq: 'u = K_p [ e / (k_b^2 - e^2) ] - K_d v + kr', tuning: 'Kb是不可跨越的生死边界。稍微逼近边界，控制推力就能指数级起飞，像隐形墙一样将轨迹弹回。', params: { kb: [6.0, 1, 15, 0.1], kp: [20, 1, 50, 1], kd: [10, 0, 20, 0.1] } },
            'ETC': { category: '07. 前沿与新型约束', name: '事件触发控制 (ETC)', desc: '为节省带宽区间保持力度，表现为锯齿状掉落-拉回。', eq: 'u(t)=u(t_k) \\ 触发: |e(t)-e(t_k)| > σ|e(t)| + ε₀', tuning: 'Sigma越大网络带宽节省越极致。注意看红色控制力极富特色的平直阶跃，即不更新网络报文的省流时刻。', params: { sigma: [0.15, 0.01, 0.5, 0.01], kp: [40, 1, 100, 1], kd: [20, 0.1, 50, 0.1], eps0: [0.05, 0.01, 0.5, 0.01] } },
            'Switched': { category: '07. 前沿与新型约束', name: '切换系统/驻留时间 (Switched)', desc: '多控制器利用李雅普诺夫衰减和驻留时间强硬调度。', eq: 'u = u_{fast} (V>1) \\ | \\ u_{slow} (V≤1)', tuning: 'Dwell(驻留时间)是防抖基石。若无驻留间隔强行插补，两套子系统频密切换必然诱发Zeno恶性震荡发散。', params: { p_fast: [4, 1, 10, 0.1], p_slow: [2, 0.1, 5, 0.1], dwell: [0.5, 0.1, 2, 0.1] } },
            'DynPole': { category: '07. 前沿与新型约束', name: '动态极点配置', desc: '根据误差游走复平面极点。误差大退守，小则深埋光速收敛。', eq: 'u = -k_1(e)x - k_2(e)v + (k_1(e)+k)r', tuning: 'Alpha_p控制游移敏捷性。大偏差拉远极点为防执行器过饱和，贴近目标拉近极点为极致精度无情镇压。', params: { p_max: [5, 1, 15, 0.1], p_min: [2, 0.1, 5, 0.1], alpha_p: [1, 0.1, 10, 0.1] } },
            'PTC': { category: '07. 前沿与新型约束', name: '预设时间控制 (PTC)', desc: '硬核承诺！无论初始状态如何，保证在指定的绝对时间内收敛。', eq: 'u = kx+cv + m( K_p e / t_{eff}^2 - K_d v / t_{eff} )', tuning: 'T_p即Deadline！系统逼近该时间点时，无论差距多大都会爆发出几何级增长控制力强行拉平误差。', params: { Tp: [2.0, 0.5, 5.0, 0.1], kp: [2.0, 0.1, 10.0, 0.1], kd: [3.0, 0.1, 10.0, 0.1], eps: [0.05, 0.01, 0.5, 0.01] } },
            'FxTC': { category: '07. 前沿与新型约束', name: '固定时间控制 (FxTC)', desc: '无论初值多大，收敛时间永远存在一个固定的理论上界。', eq: 'u = K_1 e^{p/q} + K_2 e^{r/s} \\ (p/q>1, r/s<1)', tuning: '融合了大误差域的高次幂和小误差域的低次幂，全域暴力。K1/K2直接决定固定时间上界，调大即秒杀。', params: { k1: [10, 1, 50, 1], k2: [15, 1, 50, 1], p_q: [1.2, 1.05, 2.0, 0.05], r_s: [0.8, 0.1, 0.95, 0.05] } },
            'Tan-BLF': { category: '07. 前沿与新型约束', name: '正切障碍李雅普诺夫', desc: '利用正切函数制造无穷边界，处理全状态约束。', eq: 'u = K_p e \\sec^2(\\frac{π e^2}{2 k_b^2}) - K_d v', tuning: '与对数BLF类似，但使用三角函数包裹。Kb仍是生死线。一旦触线sec函数爆发无穷大斥力。', params: { kb: [6.0, 1, 15, 0.1], kp: [20, 1, 50, 1], kd: [10, 0.1, 20, 0.1] } },
            'TimeVary-BLF': { category: '07. 前沿与新型约束', name: '时变障碍李雅普诺夫', desc: '墙壁像液压机一样不断向内压缩，逼迫状态强行收敛。', eq: 'u = K_p e / (k_b(t)^2 - e^2)', tuning: 'Lb 是墙壁向内压拢的速度。非常凶残，它等于把BLF和PPC结合在了一起，必须确保滑块跑得比墙缩得快。', params: { kb0: [6.0, 1, 15, 0.1], kb_inf: [0.5, 0.1, 2.0, 0.1], lb: [0.5, 0.1, 2.0, 0.1], kp: [20, 1, 50, 1], kd: [15, 0.1, 30, 0.1] } },
            'Integral-BLF': { category: '07. 前沿与新型约束', name: '积分障碍李雅普诺夫', desc: '给积分器套上枷锁，防止普通抗饱和算法中的反算延迟。', eq: 'u = PID... with BLF on ∫e', tuning: '极其适合高精度加工领域。它在源头上扼杀了积分超调的可能性。', params: { kb_i: [10.0, 1, 50, 0.5], kp: [40, 1, 100, 1], ki: [10, 0.1, 50, 0.1], kd: [20, 0.1, 50, 0.1] } },

            // === 【8. 轨迹规划与学习】 ===
            'InputShaping': { category: '08. 轨迹规划与学习', name: '输入整形控制 (ZV Shaper)', desc: '利用固有频率延时裂变脉冲指令，相消干涉彻底抹除震荡。', eq: 'u = K_p(r_{shaped} - x) - K_d v + k r_{shaped}', tuning: '极度硬核的高级数控机床开环技术。假设模型绝对准确，观察紫色的“楼梯前馈”，正巧利用时差完美抵消回弹。', params: { kp: [40, 1, 100, 1], kd: [20, 0.1, 50, 0.1] } },
            'ILC': { category: '08. 轨迹规划与学习', name: '迭代学习控制 (ILC)', desc: '每次目标跳变视为一轮新Trial，利用上一轮同时间点误差叠加控制增量。', eq: 'u_k(t) = u_{k-1}(t) + Γ e_k(t) + kr', tuning: '多次触发目标突变跳变(模拟Trial)！Gamma_ilc控制吸收教训比重，轨迹将愈发变态平滑。', params: { gamma_ilc: [1.0, 0.05, 2, 0.05], kp_base: [10, 0, 50, 1] } },
            'Repetitive': { category: '08. 轨迹规划与学习', name: '重复控制 (RC)', desc: '内模原理离散实现，通过延迟线记忆周期误差并反相叠加补偿。', eq: 'u(t) = Q·u(t-L) + K_{rc} e(t-L) + PD + kr', tuning: 'Q_filter防高频噪声无限内卷发散的救命稻草(略<1)。对持续不断固定模式波形干扰有绝对碾压抹除特攻。', params: { k_rc: [5, 0.1, 20, 0.1], q_filter: [0.95, 0.5, 1, 0.01] } },
            'GainSched': { category: '08. 轨迹规划与学习', name: '增益调度控制 (Gain Scheduling)', desc: '在“激进”与“保守”两组参数间极其平滑地非线性插值。', eq: 'u = K_p(|e|) e - K_d v + kr', tuning: '利用插值系数将狂暴高P增益自然过渡到绵柔低P增益，业界搞定严重非线性非定常系统最务实一手。', params: { kp_far: [60, 10, 150, 1], kp_near: [20, 1, 50, 1], bnd: [2, 0.1, 10, 0.1] } },
            'SmithPredict': { category: '08. 轨迹规划与学习', name: '史密斯预估补偿 (Smith Predictor)', desc: '利用模型将纯大滞后时间剥离出反馈死循环。', eq: 'u = C(s) [ r - y - (ŷ - ŷ_{delay}) ]', tuning: '专治大迟延。Delay_T(迟延预判)如果和真实物理迟延严丝合缝，系统的响应如无滞后般迅猛。', params: { kp: [20, 1, 50, 1], kd: [10, 0.1, 20, 0.1], delay_t: [0.5, 0.05, 2.0, 0.05] } },
            'Posicast': { category: '08. 轨迹规划与学习', name: 'Posicast 前馈补偿', desc: '利用开环半周期衰减阶跃技术切分输入指令波。', eq: 'r_{mod} = r(t) + K_{pos} r(t-Td)', tuning: '与输入整形异曲同工。K_pos 依据阻尼比推算，若物理阻尼低，会自动反相发射反冲波抵消抖动。', params: { kp: [40, 1, 100, 1], kd: [20, 0.1, 50, 0.1], k_pos: [0.3, 0, 1.0, 0.01], td: [0.3, 0.05, 1.0, 0.05] } },
            'FuzzyPID': { category: '08. 轨迹规划与学习', name: '模糊 PID', desc: '【严谨重构】结合 3x3 规则库和重心解模糊在线微调 PID 参数。', eq: 'u = (K_{p0}+ΔK_p)e + (K_{i0}+ΔK_i)∫e - (K_{d0}+ΔK_d)v', tuning: 'Range约束参数浮动警戒线。基于真实模糊推理解模糊在线修正，拒绝简单 IF-ELSE。', params: { kp0: [30, 0, 50, 1], ki0: [5, 0, 20, 0.1], kd0: [15, 0, 30, 0.1], range: [10, 1, 50, 1] } },
            'NeuralPID': { category: '08. 轨迹规划与学习', name: '神经元自适应 PID', desc: '【Hebbian神网 + PID】无监督学习在线自动进化权重。', eq: 'u = K (w_1 e + w_2 ∫e - w_3 v)', tuning: 'Eta神经突触学习率务必保持在0.01或更小，依赖缩放因子K放大动作力。能感受到权重的进化。', params: { K: [100, 1, 200, 1], eta: [0.01, 0.001, 0.1, 0.001] } },
            'Fuzzy': { category: '08. 轨迹规划与学习', name: '纯模糊控制 (Fuzzy)', desc: '【严谨重构】构建双输入单输出(e,ec)的完整模糊表面，包含模糊化与清晰化。', eq: 'u = Defuzzify( Rules( \\mu(e), \\mu(ec) ) ) · Gain', tuning: 'Ke和Kec是量化因子，保证物理误差落入模糊论域[-1, 1]。重心法运算带来的非线性曲面响应极为柔和。', params: { gain: [3, 0.1, 10, 0.1], ke: [0.5, 0.01, 1, 0.01], kec: [0.5, 0.01, 1, 0.01] } },
            'EnergyShaping': { category: '08. 轨迹规划与学习', name: '能量成型 (IDA-PBC)', desc: '【哈密顿结构重塑】修改等效势能并注入非线性阻尼。', eq: 'u = kx - K_d(x-r) - (R_0 + R_1 |v|)v', tuning: 'K_d 赋予虚拟弹簧拉力；R_0为基底阻尼，R_1为防高速猛冲的非线性截断阻尼。能量架构绝对安全无瑕。', params: { k_d: [30, 1, 100, 1], r_d0: [10, 0, 50, 0.1], r_d1: [5, 0, 20, 0.1] } },

            // === 【9. 鲁棒与现代预测】 ===
            'TubeMPC': { category: '09. 鲁棒与现代预测', name: '管式模型预测 (Tube MPC)', desc: '将名义MPC轨迹包裹在一个“鲁棒不变管”中，名义规划，局部镇定。', eq: 'u = u_{mpc}^* + K_{ancillary}(x - x_{mpc}^*)', tuning: '极富想象力的架构！K_anc为辅助镇定增益，一旦被突发扰动踢出中心轨迹，极速拉回名义管内。', params: { t_pred: [0.5, 0.05, 2.0, 0.05], lambda: [0.01, 0.001, 1, 0.001], k_anc: [30, 1, 100, 1] } },
            'SDRE': { category: '09. 鲁棒与现代预测', name: '状态相关黎卡提方程 (SDRE)', desc: 'LQR的非线性完全体。在线实时求解参数依赖的 ARE。', eq: 'u = -R^{-1} B^T P(x) x \\ (A(x)^T P + P A(x)...)', tuning: '这里采用局部近似。Q_weight 越高镇定越狂暴，完全克服了 LQR 对非线性大范围束手无策的窘境。', params: { q_weight: [100, 10, 500, 10] } },
            'GPC': { category: '09. 鲁棒与现代预测', name: '广义预测控制 (GPC)', desc: '基于 CARIMA 离散传递函数模型的长时间尺预测算子。', eq: 'Δu = (G^T G + λI)^{-1} G^T (w - f)', tuning: 'Ny为预测视野，Nu为控制视野。带有“从容不迫”的平滑感，极其适合高炉等大滞后环境。', params: { ny: [10, 1, 20, 1], nu: [3, 1, 10, 1], lam: [0.5, 0.01, 2, 0.01] } },
            'RLS-Adaptive': { category: '09. 鲁棒与现代预测', name: '在线RLS辨识自适应 (代VRFT)', desc: '【严谨重构】利用递推最小二乘法(RLS)在线辨识模型参数，反求控制器。', eq: 'θ̂ = RLS(x, u); u = K(θ̂) e', tuning: '完全摒弃原版不负责任的盲乘逻辑，系统通过记忆矩阵 P 实打实地根据历史数据纠正自身辨识参数。', params: { rls_lambda: [0.98, 0.9, 1.0, 0.01], w_bw: [5.0, 0.1, 20, 0.1] } },
            'Robust-NL-Damping': { category: '09. 鲁棒与现代预测', name: '鲁棒边界阻尼控制 (代H∞)', desc: '【严谨重构】处理有界不确定性，在无法解黎卡提方程时的降级平替。', eq: 'u = K_{nom} e - (D_{nom} + γ_d) v', tuning: '原版假借 H-infinity 之名行 PD 之实。现修正为针对最大扰动界的非线性鲁棒阻尼注入法则。', params: { kp_nom: [40, 10, 100, 1], gamma_d: [5.0, 0, 50, 0.1] } },
            'NDOB': { category: '09. 鲁棒与现代预测', name: '非线性扰动观测器 (NDOB)', desc: '基于李代数设计的全非线性观测器，无需系统逆模型即可精确估算。', eq: 'd̂ = z + p(x,v) \\ u = u_n - d̂', tuning: 'L_obs 为非线性观测器增益矩阵。相较线性DOB，能在广阔状态空间内保持无静差估算。', params: { l_obs: [20, 1, 100, 1], kp: [40, 1, 100, 1], kd: [20, 0.1, 50, 0.1] } },

            // === 【10. 观测器与网络拓扑】 ===
            'Extended-Luenberger': { category: '10. 观测器与网络拓扑', name: '扩展龙伯格观测 (E-Luenberger)', desc: '非线性系统线性化。在线雅可比矩阵求导后使用线性观测。', eq: 'dx̂/dt = f(x̂) + L(x - x̂)', tuning: 'L_gain 配置带宽。计算量远小于卡尔曼，但在突发大扰动导致局部线性化失效时容易估测崩溃。', params: { l_gain: [20, 1, 100, 1], kp: [40, 1, 100, 1], kd: [20, 0.1, 50, 0.1] } },
            'EKF-Ctrl': { category: '10. 观测器与网络拓扑', name: '扩展卡尔曼反馈 (EKF-Ctrl)', desc: '不仅过滤噪声，还能在线把未知的干扰 d 作为一个增广状态给过滤出来。', eq: 'x̂_{k+1} = ... + K_k(y - h(x̂))', tuning: 'Q_cov(过程噪声阵)和 R_cov(测量噪声阵)的黄金博弈。只要调对了，波形就像用热刀切黄油一样顺滑。', params: { q_cov: [10, 0.1, 50, 0.1], r_cov: [1, 0.1, 10, 0.1], kp: [40, 1, 100, 1], kd: [20, 0.1, 50, 0.1] } },
            'Particle-Filter': { category: '10. 观测器与网络拓扑', name: '粒子滤波反馈 (PF-Ctrl)', desc: '撒出成百上千个“粒子”在空间里试探，利用蒙特卡洛统计重采样出真实状态。', eq: 'u = K(r - ∑ w_i x_i)', tuning: '极为消耗算力(代码中精简为20个粒子)。对付非高斯噪声(比如断崖式的脉冲干扰)效果吊打卡尔曼。', params: { p_num: [20, 5, 50, 1], kp: [30, 1, 100, 1], kd: [15, 0.1, 50, 0.1] } },
            'Neural-RBF-ADRC': { category: '10. 观测器与网络拓扑', name: 'RBF神网自抗扰 (代伪Neural)', desc: '【严谨重构】布置5个高斯径向基中心点，用隐藏层输出和ESO残差在线BP训练。', eq: 'f_{NN} = ∑ w_i \\exp(-||e-c_i||^2) ; \\dot{w}_i = η e_{eso} h_i', tuning: '替换了原版挂羊头卖狗肉的代码。利用正统径向基网络逼近极其复杂的系统非线性。', params: { wo: [30, 5, 100, 1], wc: [10, 1, 50, 1], n_lr: [5.0, 0.1, 20.0, 0.1], b0: [0.5, 0.01, 5, 0.01] } },
            'Artstein-Reduction': { category: '10. 观测器与网络拓扑', name: 'Artstein 模型降阶补偿', desc: '【严谨重构】处理纯通讯迟延！利用真实的分布积分前推预判将其降阶为无迟延系统。', eq: 'z = x + ∫_{0}^d e^{As}B u(t-s) ds', tuning: '放弃了原版仅仅抽取单点延时的谬误，实施了严格的积分变换。理论上可以跨越任意极端的网络延迟。', params: { kp: [20, 1, 50, 1], kd: [10, 0.1, 30, 0.1], delay_a: [10, 1, 50, 1] } },
            'Quantized-Ctrl': { category: '10. 观测器与网络拓扑', name: '量化截断防网络阻塞', desc: '极度贫瘠的信道带宽！控制力不能是连续的，必须被强制向下取整为粗糙的阶梯量阶。', eq: 'u = Q(K_p e - K_d v) \\ Q:截断算子', tuning: 'Q_step 阶梯宽度！调大它，你会看到控制力完全变成极粗的方波，系统因此在目标点附近产生永远消不掉的量化极限环！', params: { kp: [50, 1, 150, 1], kd: [20, 0.1, 50, 0.1], q_step: [5.0, 0.5, 20.0, 0.5] } },
            'Event-Triggered-MPC': { category: '10. 观测器与网络拓扑', name: '事件触发 MPC 算力卸载', desc: 'MPC 每算一次算力消耗巨大。设定一个门槛，没越过门槛就坚决套用上一轮的预判残羹。', eq: 'Trigger QP if |x - x_{pred}| > δ', tuning: 'ET_Limit 是容忍度。它把连续的平滑预测变成了带有一点延迟顿挫的间歇性抽风控制，但给芯片省下了巨量算力。', params: { t_pred: [0.5, 0.05, 2.0, 0.05], lambda: [0.01, 0.001, 1, 0.001], et_limit: [0.2, 0.01, 1.0, 0.01] } },

            // === 【11. 高阶与物理前沿】 ===
            'FO-PD': { category: '11. 高阶与物理前沿', name: '分数阶 PD 控制 (FO-PD)', desc: '微积分项不再是整数 1，允许极其细腻的超前相位配置。利用 G-L 近似求解。', eq: 'u = K_p e + K_d D^μ e', tuning: 'Mu 决断微分强度。突破了传统PD的相位限制，能在频域上捏造出任何形状的裕度包络。', params: { kp: [40, 1, 100, 1], kd: [15, 0.1, 50, 0.1], mu: [0.8, 0.1, 1.5, 0.05] } },
            'Nonlinear-Power-ADRC': { category: '11. 高阶与物理前沿', name: '非线性次幂自抗扰 (原分数阶)', desc: '【名字修正】ESO使用分数次幂驱动，非线性极限扩张，原名产生误导。', eq: 'z_{dot} = f(z) + β |e|^α sgn(e)', tuning: 'Alpha 使得大误差收敛如虎，微小误差感知入微。是韩京清理论的直接数学泛化。', params: { wo: [30, 5, 100, 1], wc: [10, 1, 50, 1], b0: [0.5, 0.01, 5, 0.01], alpha: [0.75, 0.1, 0.99, 0.01] } },
            'Implicit-Euler-Ctrl': { category: '11. 高阶与物理前沿', name: '隐式欧拉离散控制', desc: '专为计算机仿真破局！通过后向欧拉差分，即使增益无穷大也绝不发散。', eq: 'u_k = u_{eq} + k · s_{k} / (1 + λ dt)', tuning: '这是现代数字控制的基石。不管你把 Lambda 拉到多夸张，离散系统硬是能在一步内死死抱住目标绝不抖振。', params: { c_surf: [5, 0.1, 20, 0.1], lambda: [50, 1, 200, 1] } },
            'Lorenz-Coupled': { category: '11. 高阶与物理前沿', name: '洛伦兹强迫反馈 (原混沌同步)', desc: '【严谨重构】并非加个噪声那么简单！强制物理系统的误差态反馈耦合进主混沌流形。', eq: 'u = k·e - D·v + K_c (x_{lorenz} - e)', tuning: 'Rho 是瑞利数(通常28)。控制律强制把单纯的弹簧振子拽进三维蝴蝶吸引子轨道一起陪着发疯。', params: { kp: [60, 1, 150, 1], kd: [20, 0.1, 50, 0.1], rho: [28.0, 10.0, 50.0, 1.0] } },
            'Speed-Gradient': { category: '11. 高阶与物理前沿', name: '速度梯度法 (Speed-Gradient)', desc: '俄国流派经典。强制控制变量沿着系统局部能量函数的负梯度滑落。', eq: 'u_dot = -γ ∇_u Q(x,u)', tuning: 'Gamma 是能量滑落速度。你看到的是积分形态的输出，它自带一种极其迷人的物理自稳定迟缓感。', params: { gamma_sg: [20, 1, 100, 1], q_weight: [1.0, 0.1, 10, 0.1] } },
            'Feedback-Passivation': { category: '11. 高阶与物理前沿', name: '反馈无源化 (Feedback Passivation)', desc: '用前置力矩将原本不耗散的系统“伪装”成一个自带能量耗散的无源体，再施加阻尼。', eq: 'u = u_{passify}(x) - K_v v', tuning: '极其安全！由于整个系统的能量被强制配置为恒减，只要 Kv 大于0，物理上它绝对不可能发散。', params: { kp: [30, 1, 100, 1], kv: [15, 0.1, 50, 0.1] } }
        };

const getDefaultParams = (method) => {
            const params = {};
            for (const [key, value] of Object.entries(CONTROLLER_CONFIGS[method].params)) {
                params[key] = value[0];
            }
            return params;
        };

const validateControllerConfigs = (configs = CONTROLLER_CONFIGS) => {
            for (const [id, config] of Object.entries(configs)) {
                if (!config.category || !config.name || !config.params) {
                    throw new Error(`Controller '${id}' is missing required metadata.`);
                }

                for (const [paramName, schema] of Object.entries(config.params)) {
                    if (!Array.isArray(schema) || schema.length !== 4) {
                        throw new Error(`Controller '${id}' param '${paramName}' must be [default, min, max, step].`);
                    }
                }
            }

            return true;
        };

export { DT, INITIAL_PARAMS, CONTROLLER_CONFIGS, getDefaultParams, validateControllerConfigs };
