const DICTIONARY_DATA = [
            { category: "物理对象与基础状态 (Physics & States)", color: "text-blue-600", bg: "bg-blue-50", items: [ { sym: "x", name: "实际位置 (Position)", desc: "被控物理对象当前的真实位移。" }, { sym: "v 或 ẋ", name: "实际速度 (Velocity)", desc: "位移的一阶导数。系统阻尼和电子微分阻尼的直接作用对象。" }, { sym: "a 或 ẍ", name: "实际加速度 (Acceleration)", desc: "受力与质量的比值。决定了系统动态变化的快慢。" }, { sym: "r 或 target", name: "目标指令 (Reference/Target)", desc: "希望系统追踪的理想位置设定值。" }, { sym: "u", name: "控制力/执行器输出 (Control Input)", desc: "控制器计算出的修正推力，最终作用于物理对象。" }, { sym: "m, c, k", name: "质量、阻尼、弹簧刚度", desc: "构成二阶系统动力学模型 (m·ẍ + c·ẋ + k·x = u) 的本质参数。" } ] },
            { category: "误差与基础算子 (Errors & Operators)", color: "text-teal-600", bg: "bg-teal-50", items: [ { sym: "e", name: "跟踪误差 (Tracking Error)", desc: "定义为 目标位置 减去 实际位置 (e = r - x)。一切反馈控制的源动力。" }, { sym: "∫e dt 或 ∑e", name: "误差积分 (Error Integral)", desc: "误差随时间的累积量，专治系统稳态残差(静差)。" }, { sym: "sgn(·)", name: "符号函数 (Signum)", desc: "提取变量的正负号。滑模和非线性控制中的暴力切换算子。" }, { sym: "sat(·/ε)", name: "饱和函数 (Saturation)", desc: "符号函数的柔和版。在 ε 边界层内呈现线性，边界外限幅，用于消除高频抖振(Chattering)。" }, { sym: "fal(e, α, δ)", name: "韩氏非线性函数", desc: "自抗扰控制(ADRC)核心算子，特征为“小误差大增益，大误差小增益”，有效防溢出并提速。" } ] },
            { category: "经典与增益参数 (Classical Gains)", color: "text-amber-600", bg: "bg-amber-50", items: [ { sym: "K_p", name: "比例增益 (Proportional Gain)", desc: "控制力与当前误差成正比，负责把系统快速拉向目标。" }, { sym: "K_i", name: "积分增益 (Integral Gain)", desc: "控制力与误差累积量成正比，负责消除稳态静差，但易导致超调。" }, { sym: "K_d", name: "微分增益 (Derivative Gain)", desc: "控制力与误差变化率成正比，等效于为系统注入虚拟“电子阻尼”，抑制震荡。" } ] },
            { category: "现代频域与最优控制 (Modern & Optimal)", color: "text-indigo-600", bg: "bg-indigo-50", items: [ { sym: "Q_x, Q_v", name: "状态惩罚权重矩阵 (State Penalty)", desc: "LQR等最优控制中，对误差容忍度的惩罚。值越大，系统越苛求极致精度。" }, { sym: "R 或 R_weight", name: "能量消耗惩罚权重 (Input Penalty)", desc: "对执行器出力的心疼程度。值越大，系统越“吝啬”推力，动作更绵柔。" }, { sym: "P", name: "黎卡提方程解 / 李雅普诺夫矩阵", desc: "最优控制或鲁棒控制在后台求解出的对称正定矩阵，蕴含了全局最优解的密码。" }, { sym: "t_pred 或 N_y", name: "预测视野 (Prediction Horizon)", desc: "MPC模型预测控制中，系统“向未来看”的时间跨度。" } ] },
            { category: "滑模与非线性架构 (Sliding Mode & Nonlinear)", color: "text-rose-600", bg: "bg-rose-50", items: [ { sym: "s", name: "滑模面 / 综合误差面 (Sliding Surface)", desc: "通常定义为 s = c·e + ė。将二阶控制降维为一阶。只要把状态逼迫到 s=0 的流形上，系统必稳。" }, { sym: "u_eq", name: "等效控制律 (Equivalent Control)", desc: "抵消系统已知确定性动态的基准力，维持状态在滑模面上滑动。" }, { sym: "K_gain", name: "鲁棒切换增益 (Switching Gain)", desc: "必须大于系统未知扰动的上界，用绝对暴力的来回切换强行镇压一切不确定性。" }, { sym: "ε (Epsilon)", name: "边界层厚度 (Boundary Layer)", desc: "为消除纯符号函数带来的高频剧烈抖振，而妥协退让出的一小片线性缓冲区。" } ] },
            { category: "状态观测器与自抗扰 (Observers & ADRC)", color: "text-emerald-600", bg: "bg-emerald-50", items: [ { sym: "带帽符号 (如 x̂, d̂)", name: "观测/估计值 (Estimated Value)", desc: "数学上代表并非通过传感器直接测得，而是由算法在后台推算出的数值。" }, { sym: "z_1, z_2, z_3", name: "扩张状态 (Extended States)", desc: "ESO观测器内部的虚拟世界。z1追踪位置，z2追踪速度，最神奇的z3追踪“总未知扰动”。" }, { sym: "ω_c, ω_o", name: "控制/观测带宽 (Bandwidth)", desc: "决定系统反应速度的单一旋钮。ω_o 一般设为 ω_c 的 3~5 倍以保证观测跟得上控制。" }, { sym: "b_0", name: "系统增益估计 (Control Gain)", desc: "ADRC对系统惯性的粗略认知。算法靠它将估测出的总扰动 z3 转化为补偿推力。" } ] },
            { category: "前沿约束与学习自适应 (Constraints & Adaptive)", color: "text-purple-600", bg: "bg-purple-50", items: [ { sym: "ρ(t) (Rho)", name: "规定性能漏斗边界 (PPC Funnel)", desc: "一条随时间指数收缩的绝对边界线。控制器保证误差永远不敢逾越这条漏斗线。" }, { sym: "k_b", name: "障碍李雅普诺夫墙壁 (Barrier Bound)", desc: "BLF控制中的“死亡红线”。误差一旦靠近，控制力会通过对数或正切函数爆发出无穷大斥力。" }, { sym: "θ (Theta)", name: "自适应权重参数 (Adaptive Weights)", desc: "MRAC等自适应控制中，系统在线不断摸索并修改的模型参数。" }, { sym: "γ (Gamma), η (Eta)", name: "学习率/自适应增益 (Learning Rate)", desc: "决定了系统在出错后，自我纠正、进化神经突触或参数的速度快慢。" } ] }
        ];

export { DICTIONARY_DATA };
